language: node_js
node_js: 12.16.1
install: npm install
script: npm run build
deploy:
  provider: npm
  email: "$NPM_EMAIL"
  api_key: "$NPM_API_TOKEN"
  skip_cleanup: true
  on:
    branch: master